# Generated by Django 2.2.2 on 2019-08-22 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artobject',
            name='slug',
            field=models.SlugField(default='2heb817jid', editable=False, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='product_alternative',
            name='slug',
            field=models.SlugField(default='bl7h562h9e', editable=False, max_length=200),
        ),
    ]
