# Generated by Django 2.2.2 on 2019-08-22 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0003_auto_20190822_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artobject',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product_alternative',
            name='slug',
            field=models.SlugField(default='paelu33gc3', editable=False, max_length=200),
        ),
    ]
