# Generated by Django 2.2.2 on 2019-08-22 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0004_auto_20190822_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_alternative',
            name='slug',
            field=models.SlugField(default='urbmkh6xv1', editable=False, max_length=200),
        ),
    ]
