# Generated by Django 2.2.2 on 2019-08-29 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0005_auto_20190822_1938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='cat_total',
            new_name='cart_total',
        ),
        migrations.DeleteModel(
            name='Product_alternative',
        ),
    ]
