# Generated by Django 2.2.2 on 2019-09-06 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0007_auto_20190905_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='artobject',
            name='renttime',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
