# Generated by Django 2.2.2 on 2019-09-12 14:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rentshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='rent_end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 9, 12, 14, 34, 21, 211391, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='art',
            name='rent_start_date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 9, 12, 14, 34, 21, 211391, tzinfo=utc)),
        ),
    ]
