# Generated by Django 2.2.2 on 2019-10-14 21:18

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rentshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='rent_end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 10, 14, 21, 18, 53, 774539, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='art',
            name='rent_start_date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 10, 14, 21, 18, 53, 774539, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='art',
            name='temp_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='art_renter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='crypto_wallet',
            field=models.CharField(max_length=100, unique=True, verbose_name='Public Bitcoin Address'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='private_key',
            field=models.CharField(max_length=100, unique=True, verbose_name='Crypto wallet private (secret) key'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='public_key',
            field=models.CharField(max_length=130, unique=True, verbose_name='Crypto wallet public key'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100, unique=True, verbose_name='Public Bitcoin Address')),
                ('transaction_complete', models.BooleanField(default=False)),
                ('amount_payed', models.DecimalField(decimal_places=7, max_digits=10)),
                ('exchange_rate', models.DecimalField(decimal_places=7, max_digits=10)),
                ('art_item', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='art_ordered', to='rentshop.Art')),
            ],
        ),
    ]
