# Generated by Django 2.2.2 on 2019-10-15 11:02

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rentshop', '0002_auto_20191014_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 10, 15, 11, 2, 46, 216841, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='order',
            name='order_start_date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 10, 15, 11, 2, 46, 216841, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='order',
            name='renting_person',
            field=models.CharField(blank=True, editable=False, max_length=200, verbose_name='Renting person email'),
        ),
        migrations.AlterField(
            model_name='art',
            name='rent_end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 10, 15, 11, 2, 46, 213841, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='art',
            name='rent_start_date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 10, 15, 11, 2, 46, 213841, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='art_item',
            field=models.CharField(blank=True, editable=False, max_length=200, verbose_name='Art item'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, editable=False, max_length=100, unique=True, verbose_name='Order id'),
        ),
    ]
