# Generated by Django 2.2.2 on 2019-10-30 21:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rentshop', '0003_auto_20191015_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='btc_cart_total',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='art',
            name='rent_end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 10, 30, 21, 31, 15, 122932, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='art',
            name='rent_start_date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 10, 30, 21, 31, 15, 122932, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='art_item',
            field=models.CharField(blank=True, max_length=200, verbose_name='Art item'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 10, 30, 21, 31, 15, 125932, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='Order id'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_start_date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 10, 30, 21, 31, 15, 125932, tzinfo=utc)),
        ),
    ]
