# Generated by Django 2.2.2 on 2019-11-05 12:47

import datetime

import django.db.models.deletion
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rentshop', '0004_auto_20191030_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='rent_end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 11, 5, 12, 47, 9, 196903, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='art',
            name='rent_start_date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 11, 5, 12, 47, 9, 196903, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentshop.Art'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 11, 5, 12, 47, 9, 199903, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_start_date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 11, 5, 12, 47, 9, 199903, tzinfo=utc)),
        ),
    ]
