# Generated by Django 2.2.2 on 2019-11-06 13:13

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rentshop', '0005_auto_20191105_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='btc_item_total',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='art',
            name='rent_end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 11, 6, 13, 13, 8, 918484, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='art',
            name='rent_start_date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 11, 6, 13, 13, 8, 918484, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 11, 6, 13, 13, 8, 921484, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_start_date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 11, 6, 13, 13, 8, 921484, tzinfo=utc)),
        ),
    ]
