# Generated by Django 2.2.2 on 2019-11-11 15:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rentshop', '0008_auto_20191106_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_title', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=20)),
                ('owner_email', models.CharField(max_length=100)),
                ('temp_owner_email', models.CharField(max_length=100)),
                ('rent_start_date', models.CharField(max_length=10)),
                ('rent_end_date', models.CharField(max_length=10)),
                ('payment_amount', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='art',
            name='rent_end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 11, 11, 15, 48, 20, 483876, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='art',
            name='rent_start_date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 11, 11, 15, 48, 20, 483876, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 11, 11, 15, 48, 20, 487876, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_start_date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 11, 11, 15, 48, 20, 486876, tzinfo=utc)),
        ),
    ]
