# Generated by Django 2.2.2 on 2019-11-11 15:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rentshop', '0009_auto_20191111_1648'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order_history',
            new_name='OrderHistory',
        ),
        migrations.AlterField(
            model_name='art',
            name='rent_end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 11, 11, 15, 50, 19, 973710, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='art',
            name='rent_start_date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 11, 11, 15, 50, 19, 973710, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 11, 11, 15, 50, 19, 976711, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_start_date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 11, 11, 15, 50, 19, 976711, tzinfo=utc)),
        ),
    ]
