# Generated by Django 2.2.2 on 2019-11-14 19:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rentshop', '0010_auto_20191111_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='payment_successful',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='art',
            name='rent_end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 11, 14, 19, 9, 47, 137231, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='art',
            name='rent_start_date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 11, 14, 19, 9, 47, 137231, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 11, 14, 19, 9, 47, 140231, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_start_date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 11, 14, 19, 9, 47, 140231, tzinfo=utc)),
        ),
    ]
