# Generated by Django 2.2.2 on 2019-11-16 16:19

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rentshop', '0012_auto_20191114_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='crypto_balanse',
        ),
        migrations.AlterField(
            model_name='art',
            name='rent_end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 11, 16, 16, 19, 31, 754986, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='art',
            name='rent_start_date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 11, 16, 16, 19, 31, 754986, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 11, 16, 16, 19, 31, 765987, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_start_date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 11, 16, 16, 19, 31, 765987, tzinfo=utc)),
        ),
    ]
